# Generated by Django 5.2.7 on 2025-10-23 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_admin_id_user_student_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='admin_id',
            new_name='registrar_id',
        ),
    ]
