# Generated by Django 5.2.7 on 2025-12-03 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_rename_admin_id_user_registrar_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reset_otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='reset_otp_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
