# Generated by Django 5.2.7 on 2025-10-17 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_admin_id_user_student_id'),
        ('requests', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RequestStatusLog',
            new_name='Request_Status_Log',
        ),
    ]
