# Generated by Django 5.2.7 on 2025-10-17 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0002_rename_requeststatuslog_request_status_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='proof_of_payment',
            field=models.FileField(blank=True, null=True, upload_to='payments/'),
        ),
    ]
