# Generated by Django 5.2.7 on 2025-10-17 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0003_alter_payment_proof_of_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='proof_of_payment',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
