# Generated by Django 5.2.7 on 2025-10-20 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0005_alter_payment_proof_of_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='amount',
        ),
    ]
