# Generated by Django 5.2.7 on 2025-10-23 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0006_remove_payment_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='copies',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='request',
            name='date_needed',
            field=models.DateField(blank=True, null=True),
        ),
    ]
