# Generated by Django 5.2.7 on 2025-11-02 05:43

import django.db.models.deletion
import requests.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_rename_admin_id_user_registrar_id'),
        ('requests', '0007_request_copies_request_date_needed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='proof_of_payment',
            field=models.FileField(blank=True, null=True, upload_to='payments/', validators=[requests.models.validate_file_is_image]),
        ),
        migrations.CreateModel(
            name='Claim_Slips',
            fields=[
                ('claim_id', models.AutoField(primary_key=True, serialize=False)),
                ('claim_number', models.CharField(max_length=50, unique=True)),
                ('date_ready', models.DateField()),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('issued_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_claims', to='authentication.user')),
                ('request_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claim_slips', to='requests.request')),
            ],
            options={
                'db_table': 'claim_slips',
                'ordering': ['-issued_at'],
            },
        ),
    ]
