# Generated by Django 5.2.7 on 2025-11-02 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0008_alter_payment_proof_of_payment_claim_slips'),
    ]

    operations = [
        migrations.RenameField(
            model_name='claim_slips',
            old_name='request_id',
            new_name='request',
        ),
    ]
