# Generated by Django 5.2.7 on 2025-11-02 09:23

import requests.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0009_rename_request_id_claim_slips_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='proof_of_payment',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='payments/', validators=[requests.models.validate_file_is_image]),
        ),
    ]
