# Generated by Django 5.2.7 on 2025-11-10 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0010_alter_payment_proof_of_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='request',
            new_name='request_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payment_status',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='verified_at',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='verified_by',
        ),
    ]
