# Generated by Django 5.2.7 on 2025-11-10 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0011_rename_request_payment_request_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='request_id',
            new_name='request',
        ),
    ]
