# Generated by Django 5.2.7 on 2025-11-10 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0012_rename_request_id_payment_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='request',
            field=models.OneToOneField(db_column='request_id', on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='requests.request'),
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='request',
            new_name='request_id',
        ),
    ]
