# Generated by Django 5.2.7 on 2025-11-29 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0013_alter_payment_request_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='date_ready',
            field=models.DateField(blank=True, null=True),
        ),
    ]
